// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB04GFs3Ko9KlUznILMd5_MFXXEMj8K3AU',
    appId: '1:3287239514:web:23ffd31643972749e00163',
    messagingSenderId: '3287239514',
    projectId: 'cuidador-5d99d',
    authDomain: 'cuidador-5d99d.firebaseapp.com',
    storageBucket: 'cuidador-5d99d.appspot.com',
    measurementId: 'G-26NWWW0R0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-3b4qCMc_Lg74qc9netfMvxrvCgzSu1A',
    appId: '1:3287239514:android:18af3b894bc943e6e00163',
    messagingSenderId: '3287239514',
    projectId: 'cuidador-5d99d',
    storageBucket: 'cuidador-5d99d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYkCGlRzHKguIDBi7mt4f3OhTzgz2cdPU',
    appId: '1:3287239514:ios:5e1af7f374670e38e00163',
    messagingSenderId: '3287239514',
    projectId: 'cuidador-5d99d',
    storageBucket: 'cuidador-5d99d.appspot.com',
    iosBundleId: 'com.example.cuidadorAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYkCGlRzHKguIDBi7mt4f3OhTzgz2cdPU',
    appId: '1:3287239514:ios:5e1af7f374670e38e00163',
    messagingSenderId: '3287239514',
    projectId: 'cuidador-5d99d',
    storageBucket: 'cuidador-5d99d.appspot.com',
    iosBundleId: 'com.example.cuidadorAppMobile',
  );
}
